### ISSUE TITLE
CI - are we building too much?

### ISSUE THREAD

**Issue by delicious-lemon** [mlabs-haskell/apropos-tx#12]
CI seems to be building a lot more things than it should.

**Comment by delicious-lemon** [comment]
For example. Linting in CI seems to build `hlint` and its deps from scratch which takes around 8 minutes.

**Comment by delicious-lemon** [comment]
Formatting builds `fourmolu` taking 11mins.

**Comment by jhodgdev** [comment]
To get around Slack's slow build times, we used to cache the hlint and fourmolu binaries. The problem was that because our linting and formatting checks were always breaking, the CI never cached the binaries. If they'd ever worked, they'd have cached and it wouldn't be a problem. As with #42 we will be moving away from installing them via Slack and replacing it with Nix, we should hopefully experience fewer CI failures from mismatched local- and runner- formatting tools. As it stands, even though we are installing hlint and fourmolu via nix fresh with each run, it's still as quick (if not quicker) than the cached Stack solution.

**Comment by jhodgdev** [comment]
https://github.com/mlabs-haskell/apropos-tx/actions/runs/2094750221

CI times are now down to:
  - fourmolu 1m 13s
  - hlint 48s 
  - cabal 4m 17s
